django-practice/lecture3/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.helloname, name="helloname")
]

django-practice/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('mybirthday/', include("mybirthday.urls")),
    path('todo/', include("todo.urls"))
]

django-practice/lecture3/todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

django-practice/lecture3/todo/models.py
from django.db import models

# Create your models here.

django-practice/lecture3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")
    
def helloname(request, name):
    return render(request, "hello/helloname.html", {
        "name": name
    })

django-practice/lecture3/mybirthday/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "mybirthday/index.html", {
        "ismybirthday": now.month == 11 and now.day == 11
    })

django-practice/lecture3/todo/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

class NewTodoForm(forms.Form):
    todo = forms.CharField(label="Add Todo")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)

# Create your views here.
def index(request):
    if "todos" not in request.session:
        request.session["todos"] = []

    return render(request, "todo/index.html", {
        "todos": request.session["todos"]
    })
    
def add(request):
    if request.method == "POST":
        form = NewTodoForm(request.POST)
        if form.is_valid():
            todo = form.cleaned_data["todo"]
            request.session["todos"] += [todo]
            return HttpResponseRedirect(reverse("todo:index"))
        else:
            return render(request, "todo/add.html", {
                "form": form
            })

    return render(request, "todo/add.html", {
        "form": NewTodoForm()
    })

django-practice/lecture3/hello/templates/hello/helloname.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello!</title>
  </head>
  <body>
    <p>"Hello, {{name}}!"</p>
  </body>
</html>

django-practice/lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello!</title>
  </head>
  <body>
    <p>"Hello, world!"</p>
  </body>
</html>

django-practice/lecture3/mybirthday/templates/mybirthday/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Eliska's Birthday?</title>
    <link href="{% static 'mybirthday/styles.css' %}" rel="stylesheet">
  </head>
  <body>
    {% if ismybirthday %}
      <h2>Yes!</h2>
    {% else %}
      <h2>No :(</h2>
    {% endif %}
  </body>
</html>

django-practice/lecture3/todo/templates/todo/add.html
{% extends "todo/layout.html" %}

{% block body %}
    <h1>Add Todo</h1>
    <form action="{% url 'todo:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'todo:index' %}">Back to List</a>
  {% endblock %}

django-practice/lecture3/todo/templates/todo/index.html
{% extends "todo/layout.html" %}

{% block body %}
    <h1>Todos</h1>
    <ul>
      {%for todo in todos %}
      <li>{{todo}}</li>
      {% empty %}
      <p>No Todos</p>
      {% endfor %}
    </ul>
    <a href="{% url 'todo:add'%}">Add New Todo</a>
    {% endblock %}

django-practice/lecture3/todo/templates/todo/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Todo</title>
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>